#!/usr/bin/env python3
"""Build curated simple-legit JSONL (500–1000+ diverse URLs) for training augmentation.

Run from repo root:  python scripts/build_simple_legit_urls.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Dict, List, Set, Tuple

_REPO = Path(__file__).resolve().parents[1]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from src.pipeline.clean import canonicalize_url

OutRow = Tuple[str, str]  # url, category


def _dedupe_rows(pairs: List[OutRow]) -> List[Dict[str, str]]:
    seen: Set[str] = set()
    out: List[Dict[str, str]] = []
    for url, cat in pairs:
        url = url.strip()
        if not url:
            continue
        c, inv, err = canonicalize_url(url)
        if inv or not c:
            continue
        key = c.strip().lower()
        if key in seen:
            continue
        seen.add(key)
        out.append({"url": url, "category": cat})
    return out


def _all_pairs() -> List[OutRow]:
    p: List[OutRow] = []

    def add(urls: List[str], cat: str) -> None:
        for u in urls:
            p.append((u, cat))

    # --- Homepage / portals (global) ---
    add(
        [
            "https://www.google.com/",
            "https://www.wikipedia.org/",
            "https://www.microsoft.com/",
            "https://www.apple.com/",
            "https://www.amazon.com/",
            "https://www.meta.com/",
            "https://www.ibm.com/",
            "https://www.oracle.com/",
            "https://www.intel.com/",
            "https://www.nvidia.com/",
            "https://www.cisco.com/",
            "https://www.sap.com/",
            "https://www.salesforce.com/",
            "https://www.adobe.com/",
            "https://www.autodesk.com/",
            "https://www.vmware.com/",
            "https://www.redhat.com/",
            "https://www.canonical.com/",
            "https://www.mozilla.org/",
            "https://www.python.org/",
            "https://www.php.net/",
            "https://www.ruby-lang.org/",
            "https://www.rust-lang.org/",
            "https://www.docker.com/",
            "https://www.kubernetes.io/",
            "https://www.terraform.io/",
            "https://www.jenkins.io/",
            "https://www.gitlab.com/",
            "https://www.github.com/",
            "https://www.bitbucket.org/",
            "https://www.atlassian.com/",
            "https://www.cloudflare.com/",
            "https://www.fastly.com/",
            "https://www.akamai.com/",
            "https://www.datadoghq.com/",
            "https://www.elastic.co/",
            "https://www.mongodb.com/",
            "https://www.postgresql.org/",
            "https://www.mysql.com/",
            "https://www.sqlite.org/",
            "https://www.nginx.com/",
            "https://www.apache.org/",
            "https://www.kernel.org/",
            "https://www.gnu.org/",
            "https://www.fsf.org/",
            "https://www.debian.org/",
            "https://www.ubuntu.com/",
            "https://www.archlinux.org/",
            "https://www.freebsd.org/",
            "https://www.openssl.org/",
            "https://www.w3.org/",
            "https://www.ietf.org/",
            "https://www.icann.org/",
            "https://www.iana.org/",
            "https://www.unicode.org/",
        ],
        "homepage_tech",
    )

    # --- Amazon / e‑commerce regional homepages ---
    for host, cat in [
        ("https://www.amazon.co.uk/", "ecommerce_regional"),
        ("https://www.amazon.de/", "ecommerce_regional"),
        ("https://www.amazon.fr/", "ecommerce_regional"),
        ("https://www.amazon.co.jp/", "ecommerce_regional"),
        ("https://www.amazon.ca/", "ecommerce_regional"),
        ("https://www.amazon.com.au/", "ecommerce_regional"),
        ("https://www.amazon.in/", "ecommerce_regional"),
        ("https://www.amazon.com.br/", "ecommerce_regional"),
        ("https://www.amazon.es/", "ecommerce_regional"),
        ("https://www.amazon.it/", "ecommerce_regional"),
        ("https://www.amazon.nl/", "ecommerce_regional"),
        ("https://www.amazon.se/", "ecommerce_regional"),
        ("https://www.amazon.pl/", "ecommerce_regional"),
        ("https://www.ebay.com/", "ecommerce"),
        ("https://www.ebay.co.uk/", "ecommerce_regional"),
        ("https://www.ebay.de/", "ecommerce_regional"),
        ("https://www.target.com/", "ecommerce"),
        ("https://www.walmart.com/", "ecommerce"),
        ("https://www.costco.com/", "ecommerce"),
        ("https://www.bestbuy.com/", "ecommerce"),
        ("https://www.homedepot.com/", "ecommerce"),
        ("https://www.lowes.com/", "ecommerce"),
        ("https://www.ikea.com/", "ecommerce"),
        ("https://www.zalando.com/", "ecommerce_regional"),
        ("https://www.rakuten.co.jp/", "ecommerce_regional"),
        ("https://www.flipkart.com/", "ecommerce_regional"),
        ("https://www.mercadolibre.com/", "ecommerce_regional"),
        ("https://www.alibaba.com/", "ecommerce"),
        ("https://www.etsy.com/", "ecommerce"),
        ("https://www.shopify.com/", "saas_ecommerce"),
    ]:
        p.append((host, cat))

    # --- SaaS / productivity homepages ---
    add(
        [
            "https://www.slack.com/",
            "https://www.zoom.us/",
            "https://www.dropbox.com/",
            "https://www.box.com/",
            "https://www.notion.so/",
            "https://www.figma.com/",
            "https://www.canva.com/",
            "https://www.airtable.com/",
            "https://www.hubspot.com/",
            "https://www.mailchimp.com/",
            "https://www.zendesk.com/",
            "https://www.okta.com/",
            "https://www.auth0.com/",
            "https://www.docusign.com/",
            "https://www.twilio.com/",
            "https://www.stripe.com/",
            "https://www.squareup.com/",
            "https://www.paypal.com/",
            "https://www.visa.com/",
            "https://www.mastercard.com/",
            "https://www.americanexpress.com/",
            "https://www.jira.com/",
            "https://www.trello.com/",
            "https://www.asana.com/",
            "https://www.monday.com/",
            "https://www.clickup.com/",
            "https://www.basecamp.com/",
            "https://www.intercom.com/",
            "https://www.pagerduty.com/",
            "https://www.splunk.com/",
            "https://www.tableau.com/",
            "https://www.looker.com/",
            "https://www.snowflake.com/",
            "https://www.databricks.com/",
            "https://www.palantir.com/",
            "https://www.openai.com/",
            "https://www.anthropic.com/",
            "https://www.cohere.com/",
            "https://www.huggingface.co/",
            "https://www.reddit.com/",
            "https://www.linkedin.com/",
            "https://www.twitter.com/",
            "https://www.quora.com/",
            "https://www.medium.com/",
            "https://www.substack.com/",
        ],
        "saas_homepage",
    )

    # --- News / docs / blogs (global) ---
    add(
        [
            "https://www.bbc.com/",
            "https://www.bbc.co.uk/",
            "https://www.reuters.com/",
            "https://www.ap.org/",
            "https://www.npr.org/",
            "https://www.pbs.org/",
            "https://www.cnn.com/",
            "https://www.nytimes.com/",
            "https://www.washingtonpost.com/",
            "https://www.theguardian.com/",
            "https://www.ft.com/",
            "https://www.economist.com/",
            "https://www.bloomberg.com/",
            "https://www.wsj.com/",
            "https://www.usatoday.com/",
            "https://www.latimes.com/",
            "https://www.chicagotribune.com/",
            "https://www.spiegel.de/",
            "https://www.zeit.de/",
            "https://www.faz.net/",
            "https://www.lemonde.fr/",
            "https://www.lefigaro.fr/",
            "https://www.elpais.com/",
            "https://www.corriere.it/",
            "https://www.repubblica.it/",
            "https://www.nos.nl/",
            "https://www.volkskrant.nl/",
            "https://www.aftonbladet.se/",
            "https://www.dn.se/",
            "https://www.hs.fi/",
            "https://www.dr.dk/",
            "https://www.nrk.no/",
            "https://www.vg.no/",
            "https://www.politico.eu/",
            "https://www.euronews.com/",
            "https://www.aljazeera.com/",
            "https://www.bbc.com/news",
        ],
        "news_media",
    )

    # --- Asia–Pacific news & portals ---
    add(
        [
            "https://www.nhk.or.jp/",
            "https://www.asahi.com/",
            "https://www.yomiuri.co.jp/",
            "https://www.sankei.com/",
            "https://www.straitstimes.com/",
            "https://www.channelnewsasia.com/",
            "https://www.scmp.com/",
            "https://www.thehindu.com/",
            "https://www.timesofindia.com/",
            "https://www.indianexpress.com/",
            "https://www.koreaherald.com/",
            "https://www.japantimes.co.jp/",
            "https://www.abs-cbn.com/",
            "https://www.bangkokpost.com/",
            "https://www.smh.com.au/",
            "https://www.theage.com.au/",
            "https://www.abc.net.au/",
            "https://www.news.com.au/",
            "https://www.stuff.co.nz/",
            "https://www.nzherald.co.nz/",
        ],
        "news_regional_apac",
    )

    # --- .edu (US & international English) ---
    add(
        [
            "https://www.mit.edu/",
            "https://www.stanford.edu/",
            "https://www.harvard.edu/",
            "https://www.berkeley.edu/",
            "https://www.ucla.edu/",
            "https://www.cmu.edu/",
            "https://www.cornell.edu/",
            "https://www.yale.edu/",
            "https://www.princeton.edu/",
            "https://www.columbia.edu/",
            "https://www.nyu.edu/",
            "https://www.utexas.edu/",
            "https://www.umich.edu/",
            "https://www.wisc.edu/",
            "https://www.washington.edu/",
            "https://www.caltech.edu/",
            "https://www.gatech.edu/",
            "https://www.purdue.edu/",
            "https://www.uiuc.edu/",
            "https://www.unc.edu/",
            "https://www.duke.edu/",
            "https://www.northwestern.edu/",
            "https://www.upenn.edu/",
            "https://www.jhu.edu/",
            "https://www.brown.edu/",
            "https://www.dartmouth.edu/",
            "https://www.rice.edu/",
            "https://www.vanderbilt.edu/",
            "https://www.emory.edu/",
            "https://www.usc.edu/",
            "https://www.asu.edu/",
            "https://www.osu.edu/",
            "https://www.psu.edu/",
            "https://www.rutgers.edu/",
            "https://www.virginia.edu/",
            "https://www.umd.edu/",
            "https://www.ufl.edu/",
            "https://www.ncsu.edu/",
            "https://www.colorado.edu/",
            "https://www.oregonstate.edu/",
            "https://www.cam.ac.uk/",
            "https://www.ox.ac.uk/",
            "https://www.imperial.ac.uk/",
            "https://www.ucl.ac.uk/",
            "https://www.ed.ac.uk/",
            "https://www.manchester.ac.uk/",
            "https://www.kcl.ac.uk/",
            "https://www.toronto.edu/",
            "https://www.ubc.ca/",
            "https://www.mcgill.ca/",
            "https://www.unsw.edu.au/",
            "https://www.sydney.edu.au/",
            "https://www.anu.edu.au/",
            "https://www.tsinghua.edu.cn/",
            "https://www.pku.edu.cn/",
            "https://www.iitb.ac.in/",
            "https://www.iisc.ac.in/",
        ],
        "edu",
    )

    # --- Government / IGO ---
    add(
        [
            "https://www.usa.gov/",
            "https://www.nasa.gov/",
            "https://www.nih.gov/",
            "https://www.cdc.gov/",
            "https://www.fda.gov/",
            "https://www.uspto.gov/",
            "https://www.state.gov/",
            "https://www.defense.gov/",
            "https://www.energy.gov/",
            "https://www.commerce.gov/",
            "https://www.justice.gov/",
            "https://www.treasury.gov/",
            "https://www.epa.gov/",
            "https://www.noaa.gov/",
            "https://www.usgs.gov/",
            "https://www.nsf.gov/",
            "https://www.whitehouse.gov/",
            "https://www.congress.gov/",
            "https://www.supremecourt.gov/",
            "https://www.un.org/",
            "https://www.who.int/",
            "https://www.worldbank.org/",
            "https://www.imf.org/",
            "https://www.oecd.org/",
            "https://www.nato.int/",
            "https://www.europa.eu/",
            "https://european-union.europa.eu/",
            "https://www.gov.uk/",
            "https://www.canada.ca/",
            "https://www.australia.gov.au/",
            "https://www.gov.br/",
            "https://www.gob.mx/",
            "https://www.gob.es/",
            "https://www.gouvernement.fr/",
            "https://www.bund.de/",
            "https://www.rijksoverheid.nl/",
            "https://www.gov.sg/",
            "https://www.gov.in/",
            "https://www.gov.za/",
            "https://www.japan.go.jp/",
        ],
        "gov_igo",
    )

    # --- NGOs / standards / science ---
    add(
        [
            "https://www.wikipedia.org/",
            "https://en.wikipedia.org/wiki/Main_Page",
            "https://species.wikimedia.org/",
            "https://www.wikimedia.org/",
            "https://www.mozilla.org/en-US/",
            "https://www.eff.org/",
            "https://www.aclu.org/",
            "https://www.greenpeace.org/",
            "https://www.amnesty.org/",
            "https://www.doctorswithoutborders.org/",
            "https://www.redcross.org/",
            "https://www.unicef.org/",
            "https://www.si.edu/",
            "https://www.nature.com/",
            "https://www.science.org/",
            "https://www.thelancet.com/",
            "https://www.ieee.org/",
            "https://www.acm.org/",
            "https://www.aaas.org/",
            "https://www.royalsociety.org/",
        ],
        "ngo_science",
    )

    # --- Entertainment / sports (official) ---
    add(
        [
            "https://www.netflix.com/",
            "https://www.spotify.com/",
            "https://www.disney.com/",
            "https://www.warnerbros.com/",
            "https://www.sonypictures.com/",
            "https://www.nintendo.com/",
            "https://www.playstation.com/",
            "https://www.xbox.com/",
            "https://www.ea.com/",
            "https://www.ubisoft.com/",
            "https://www.fifa.com/",
            "https://www.uefa.com/",
            "https://www.nba.com/",
            "https://www.nfl.com/",
            "https://www.mlb.com/",
            "https://www.nhl.com/",
            "https://www.formula1.com/",
            "https://www.olympics.com/",
            "https://www.espn.com/",
            "https://www.skysports.com/",
        ],
        "entertainment_sports",
    )

    # --- Automotive / travel / hospitality ---
    add(
        [
            "https://www.toyota.com/",
            "https://www.ford.com/",
            "https://www.gm.com/",
            "https://www.bmw.com/",
            "https://www.mercedes-benz.com/",
            "https://www.volkswagen.com/",
            "https://www.honda.com/",
            "https://www.hyundai.com/",
            "https://www.renaultgroup.com/",
            "https://www.stellantis.com/",
            "https://www.marriott.com/",
            "https://www.hilton.com/",
            "https://www.hyatt.com/",
            "https://www.accor.com/",
            "https://www.booking.com/",
            "https://www.expedia.com/",
            "https://www.tripadvisor.com/",
            "https://www.airbnb.com/",
            "https://www.delta.com/",
            "https://www.united.com/",
            "https://www.americanairlines.com/",
            "https://www.lufthansa.com/",
            "https://www.britishairways.com/",
            "https://www.emirates.com/",
            "https://www.qatarairways.com/",
            "https://www.singaporeair.com/",
            "https://www.jal.co.jp/",
            "https://www.ana.co.jp/",
        ],
        "travel_auto",
    )

    # --- Telecom / utilities ---
    add(
        [
            "https://www.verizon.com/",
            "https://www.att.com/",
            "https://www.t-mobile.com/",
            "https://www.vodafone.com/",
            "https://www.telefonica.com/",
            "https://www.orange.com/",
            "https://www.deutschetelekom.de/",
            "https://www.bt.com/",
            "https://www.telstra.com.au/",
            "https://www.singtel.com/",
            "https://www.ntt.com/",
            "https://www.kddi.com/",
        ],
        "telecom",
    )

    # --- Financial institutions (homepages only) ---
    add(
        [
            "https://www.jpmorganchase.com/",
            "https://www.bankofamerica.com/",
            "https://www.citi.com/",
            "https://www.wellsfargo.com/",
            "https://www.goldmansachs.com/",
            "https://www.morganstanley.com/",
            "https://www.blackrock.com/",
            "https://www.vanguard.com/",
            "https://www.fidelity.com/",
            "https://www.schwab.com/",
            "https://www.hsbc.com/",
            "https://www.barclays.co.uk/",
            "https://www.lloydsbank.com/",
            "https://www.natwest.com/",
            "https://www.bnpparibas.com/",
            "https://www.societegenerale.com/",
            "https://www.deutsche-bank.de/",
            "https://www.ubs.com/",
            "https://www.credit-suisse.com/",
            "https://www.ing.com/",
            "https://www.rabobank.com/",
            "https://www.commbank.com.au/",
            "https://www.boc.cn/",
            "https://www.icbc.com.cn/",
            "https://www.mufg.jp/",
        ],
        "finance_homepage",
    )

    # --- Consumer brands / retail ---
    add(
        [
            "https://www.nike.com/",
            "https://www.adidas.com/",
            "https://www.unilever.com/",
            "https://www.nestle.com/",
            "https://www.coca-cola.com/",
            "https://www.pepsico.com/",
            "https://www.mcdonalds.com/",
            "https://www.starbucks.com/",
            "https://www.subway.com/",
            "https://www.lego.com/",
            "https://www.mattel.com/",
            "https://www.hasbro.com/",
        ],
        "consumer_brand",
    )

    # --- Industrial / energy ---
    add(
        [
            "https://www.shell.com/",
            "https://www.bp.com/",
            "https://www.totalenergies.com/",
            "https://www.chevron.com/",
            "https://www.exxonmobil.com/",
            "https://www.siemens.com/",
            "https://www.ge.com/",
            "https://www.bosch.com/",
            "https://www.schneider-electric.com/",
            "https://www.abb.com/",
            "https://www.caterpillar.com/",
            "https://www.deere.com/",
        ],
        "industrial_energy",
    )

    # --- Wikipedia language portals (diverse ccTLD / structure) ---
    for code in (
        "de",
        "fr",
        "es",
        "it",
        "pt",
        "nl",
        "pl",
        "ru",
        "ja",
        "zh",
        "ko",
        "ar",
        "hi",
        "tr",
        "sv",
        "no",
        "da",
        "fi",
        "cs",
        "he",
        "id",
        "th",
        "vi",
        "uk",
        "ro",
        "hu",
        "el",
        "ca",
        "sr",
        "fa",
    ):
        p.append((f"https://{code}.wikipedia.org/wiki/Main_Page", "wikipedia_lang_portal"))

    # --- Regional & country sites (more TLD diversity) ---
    add(
        [
            "https://www.bbc.in/",
            "https://www.gov.ie/",
            "https://www.gov.wales/",
            "https://www.scotland.org/",
            "https://www.belgium.be/",
            "https://www.luxembourg.lu/",
            "https://www.ch.ch/",
            "https://www.li.li/",
            "https://www.island.is/",
            "https://www.norge.no/",
            "https://www.suomi.fi/",
            "https://www.latvija.lv/",
            "https://www.lietuva.lt/",
            "https://www.eesti.ee/",
            "https://www.gov.cy/",
            "https://www.malta.gov.mt/",
            "https://www.gov.gr/",
            "https://www.gov.pt/",
            "https://www.argentina.gob.ar/",
            "https://www.gob.cl/",
            "https://www.gob.pe/",
            "https://www.gov.co/",
            "https://www.nigeria.gov.ng/",
            "https://www.kenya.go.ke/",
            "https://www.gov.eg/",
            "https://www.gov.sa/",
            "https://www.gov.ae/",
            "https://www.gov.qa/",
            "https://www.gov.kw/",
            "https://www.data.gov/",
            "https://www.archives.gov/",
            "https://www.loc.gov/",
            "https://www.si.edu/",
        ],
        "gov_regional",
    )

    # --- Developer docs & package registries (clean informational) ---
    add(
        [
            "https://docs.python.org/3/",
            "https://developer.mozilla.org/",
            "https://nodejs.org/",
            "https://go.dev/",
            "https://www.rust-lang.org/learn",
            "https://doc.rust-lang.org/book/",
            "https://learn.microsoft.com/",
            "https://cloud.google.com/docs",
            "https://docs.aws.amazon.com/",
            "https://learn.openapis.org/",
            "https://semver.org/",
            "https://keepachangelog.com/",
            "https://choosealicense.com/",
            "https://pypi.org/",
            "https://crates.io/",
            "https://www.nuget.org/",
            "https://packagist.org/",
        ],
        "docs_dev",
    )

    # --- More global brands / localized corporate ---
    add(
        [
            "https://www.samsung.com/",
            "https://www.lg.com/",
            "https://www.sony.com/",
            "https://www.panasonic.com/",
            "https://www.philips.com/",
            "https://www.dell.com/",
            "https://www.lenovo.com/",
            "https://www.hp.com/",
            "https://www.asus.com/",
            "https://www.acer.com/",
            "https://www.msi.com/",
            "https://www.logitech.com/",
            "https://www.corsair.com/",
            "https://www.soundcloud.com/",
            "https://www.bandcamp.com/",
            "https://www.archive.org/",
            "https://www.gutenberg.org/",
        ],
        "brand_global",
    )

    # --- Additional US & international universities ---
    add(
        [
            "https://www.bu.edu/",
            "https://www.tufts.edu/",
            "https://www.bc.edu/",
            "https://www.wpi.edu/",
            "https://www.brandeis.edu/",
            "https://www.temple.edu/",
            "https://www.drexel.edu/",
            "https://www.gwu.edu/",
            "https://www.georgetown.edu/",
            "https://www.vt.edu/",
            "https://www.wm.edu/",
            "https://www.wfu.edu/",
            "https://www.tulane.edu/",
            "https://www.baylor.edu/",
            "https://www.tcu.edu/",
            "https://www.smu.edu/",
            "https://www.utexas.edu/",
            "https://www.tamu.edu/",
            "https://www.ttu.edu/",
            "https://www.ou.edu/",
            "https://www.ku.edu/",
            "https://www.k-state.edu/",
            "https://www.iastate.edu/",
            "https://www.missouri.edu/",
            "https://www.uky.edu/",
            "https://www.louisville.edu/",
            "https://www.vcu.edu/",
            "https://www.gmu.edu/",
            "https://www.jmu.edu/",
            "https://www.clemson.edu/",
            "https://www.sc.edu/",
            "https://www.uga.edu/",
            "https://www.fsu.edu/",
            "https://www.ucf.edu/",
            "https://www.fiu.edu/",
            "https://www.miami.edu/",
            "https://www.uab.edu/",
            "https://www.uah.edu/",
            "https://www.auburn.edu/",
            "https://www.uark.edu/",
            "https://www.uoregon.edu/",
            "https://www.pdx.edu/",
            "https://www.uidaho.edu/",
            "https://www.montana.edu/",
            "https://www.usu.edu/",
            "https://www.unm.edu/",
            "https://www.nmsu.edu/",
            "https://www.unlv.edu/",
            "https://www.unr.edu/",
            "https://www.unl.edu/",
            "https://www.ndsu.edu/",
            "https://www.sdsu.edu/",
            "https://www.siu.edu/",
            "https://www.uic.edu/",
            "https://www.iit.edu/",
            "https://www.luc.edu/",
            "https://www.marquette.edu/",
            "https://www.uwm.edu/",
            "https://www.uwec.edu/",
            "https://www.uwlax.edu/",
            "https://www.binghamton.edu/",
            "https://www.albany.edu/",
            "https://www.stonybrook.edu/",
            "https://www.buffalo.edu/",
            "https://www.uri.edu/",
            "https://www.uconn.edu/",
            "https://www.uvm.edu/",
            "https://www.unh.edu/",
            "https://www.maine.edu/",
            "https://www.udel.edu/",
            "https://www.lehigh.edu/",
            "https://www.bucknell.edu/",
            "https://www.lafayette.edu/",
            "https://www.swarthmore.edu/",
            "https://www.haverford.edu/",
            "https://www.brynmawr.edu/",
            "https://www.wellesley.edu/",
            "https://www.smith.edu/",
            "https://www.mtholyoke.edu/",
            "https://www.amherst.edu/",
            "https://www.williams.edu/",
            "https://www.middlebury.edu/",
            "https://www.colby.edu/",
            "https://www.bates.edu/",
            "https://www.bowdoin.edu/",
            "https://www.colgate.edu/",
            "https://www.hamilton.edu/",
            "https://www.skidmore.edu/",
            "https://www.union.edu/",
            "https://www.stlawu.edu/",
            "https://www.stolaf.edu/",
            "https://www.macalester.edu/",
            "https://www.carleton.edu/",
            "https://www.grinnell.edu/",
            "https://www.knox.edu/",
            "https://www.oberlin.edu/",
            "https://www.kenyon.edu/",
            "https://www.denison.edu/",
            "https://www.depauw.edu/",
            "https://www.wooster.edu/",
            "https://www.earlham.edu/",
            "https://www.uchicago.edu/",
            "https://www.northwestern.edu/",
        ],
        "edu_us_more",
    )

    # --- EU national / city portals & institutions ---
    add(
        [
            "https://www.bundestag.de/",
            "https://www.bundesregierung.de/",
            "https://www.polizei.de/",
            "https://www.bmi.bund.de/",
            "https://www.elysee.fr/",
            "https://www.assemblee-nationale.fr/",
            "https://www.senat.fr/",
            "https://www.congreso.es/",
            "https://www.lamoncloa.gob.es/",
            "https://www.camera.it/",
            "https://www.parlamento.it/",
            "https://www.stortinget.no/",
            "https://www.riksdagen.se/",
            "https://www.eduskunta.fi/",
            "https://www.gov.mt/",
            "https://www.irishstatutebook.ie/",
            "https://www.oireachtas.ie/",
            "https://www.publichealth.ie/",
            "https://www.nhs.uk/",
            "https://www.nibusinessinfo.co.uk/",
            "https://www.scotland.org/",
            "https://www.visitwales.com/",
            "https://www.northernireland.gov.uk/",
            "https://www.culture.gov.uk/",
            "https://www.royal.uk/",
            "https://www.monarchie.be/",
            "https://www.parlament.ch/",
            "https://www.admin.ch/",
            "https://www.vienna.at/",
            "https://www.wien.gv.at/",
            "https://www.berlin.de/",
            "https://www.muenchen.de/",
            "https://www.frankfurt.de/",
            "https://www.hamburg.de/",
            "https://www.stadt-koeln.de/",
            "https://www.paris.fr/",
            "https://www.lyon.fr/",
            "https://www.marseille.fr/",
            "https://www.barcelona.cat/",
            "https://www.madrid.es/",
            "https://www.comune.roma.it/",
            "https://www.comune.milano.it/",
            "https://www.amsterdam.nl/",
            "https://www.rotterdam.nl/",
            "https://www.denhaag.nl/",
            "https://www.brussels.be/",
            "https://www.antwerpen.be/",
            "https://www.gent.be/",
            "https://www.zuerich.ch/",
            "https://www.stadt-zuerich.ch/",
            "https://www.geneve.ch/",
            "https://www.luzern.ch/",
            "https://www.baselstadt.ch/",
            "https://www.dublin.ie/",
            "https://www.corkcity.ie/",
            "https://www.limerick.ie/",
            "https://www.galway.ie/",
            "https://www.praha.eu/",
            "https://www.brno.cz/",
            "https://www.warszawa.pl/",
            "https://www.krakow.pl/",
            "https://www.wroclaw.pl/",
            "https://www.budapest.hu/",
            "https://www.bucharest.ro/",
            "https://www.cluj-napoca.ro/",
            "https://www.sofia.bg/",
            "https://www.zagreb.hr/",
            "https://www.ljubljana.si/",
            "https://www.luxembourg.public.lu/",
        ],
        "eu_city_institution",
    )

    # --- Latin America & Caribbean official / major media ---
    add(
        [
            "https://www.gob.ar/",
            "https://www.argentina.gob.ar/",
            "https://www.buenosaires.gob.ar/",
            "https://www.rio.rj.gov.br/",
            "https://www.prefeitura.sp.gov.br/",
            "https://www.df.gov.br/",
            "https://www.gob.mx/",
            "https://www.cdmx.gob.mx/",
            "https://www.colombia.co/",
            "https://www.mincit.gov.co/",
            "https://www.presidencia.gov.co/",
            "https://www.gob.pe/",
            "https://www.munlima.gob.pe/",
            "https://www.gob.cl/",
            "https://www.chile.gob.cl/",
            "https://www.uruguay.gub.uy/",
            "https://www.gub.uy/",
            "https://www.presidencia.gub.uy/",
            "https://www.paraguay.gov.py/",
            "https://www.presidencia.gov.py/",
            "https://www.bolivia.gob.bo/",
            "https://www.ecuador.gob.ec/",
            "https://www.presidencia.gob.ec/",
            "https://www.presidencia.gov.ve/",
            "https://www.gobiernobolivariano.gob.ve/",
            "https://www.jamaica.gov.jm/",
            "https://www.gov.bb/",
            "https://www.gov.ky/",
            "https://www.gov.tt/",
            "https://www.clarin.com/",
            "https://www.lanacion.com.ar/",
            "https://www.ambito.com/",
            "https://www.infobae.com/",
            "https://oglobo.globo.com/",
            "https://www.estadao.com.br/",
            "https://www.folha.uol.com.br/",
            "https://www.eluniversal.com.mx/",
            "https://www.reforma.com/",
            "https://www.latercera.com/",
            "https://www.emol.com/",
            "https://www.elcomercio.pe/",
            "https://www.larepublica.pe/",
        ],
        "latam_media_gov",
    )

    # --- Africa & Middle East news / gov ---
    add(
        [
            "https://www.gov.za/",
            "https://www.parliament.gov.za/",
            "https://www.sanews.gov.za/",
            "https://www.nigeria.gov.ng/",
            "https://www.presidency.gov.ng/",
            "https://www.kenya.go.ke/",
            "https://www.parliament.go.ke/",
            "https://www.egypt.gov.eg/",
            "https://www.presidency.eg/",
            "https://www.sis.gov.eg/",
            "https://www.morocco.ma/",
            "https://www.maroc.ma/",
            "https://www.tunisia.tn/",
            "https://www.presidence.tn/",
            "https://www.algeria.gov.dz/",
            "https://www.ethiopia.gov.et/",
            "https://www.gov.et/",
            "https://www.rwandagov.rw/",
            "https://www.gov.rw/",
            "https://www.ghana.gov.gh/",
            "https://www.parliament.gh/",
            "https://www.senegal.gouv.sn/",
            "https://www.presidence.sn/",
            "https://www.cotedivoire.ci/",
            "https://www.gouv.ci/",
            "https://www.tanzania.go.tz/",
            "https://www.uganda.go.ug/",
            "https://www.gov.ug/",
            "https://www.malawi.gov.mw/",
            "https://www.zambia.gov.zm/",
            "https://www.gov.zm/",
            "https://www.botswana.gov.bw/",
            "https://www.namibia.gov.na/",
            "https://www.moj.gov.jo/",
            "https://www.pm.gov.jo/",
            "https://www.lebanon.gov.lb/",
            "https://www.pcm.gov.lb/",
            "https://www.moi.gov.kw/",
            "https://www.e.gov.kw/",
            "https://www.bahrain.bh/",
            "https://www.pm.gov.bh/",
            "https://www.oman.om/",
            "https://www.majlisoman.om/",
        ],
        "africa_me_gov_news",
    )

    # --- Asia more: corporate & gov ---
    add(
        [
            "https://www.gov.cn/",
            "https://www.mfa.gov.cn/",
            "https://www.mohrss.gov.cn/",
            "https://www.mof.gov.jp/",
            "https://www.mhlw.go.jp/",
            "https://www.meti.go.jp/",
            "https://www.mlit.go.jp/",
            "https://www.mofa.go.kr/",
            "https://www.moleg.go.kr/",
            "https://www.gov.tw/",
            "https://www.president.gov.tw/",
            "https://www.india.gov.in/",
            "https://www.pib.gov.in/",
            "https://www.meity.gov.in/",
            "https://www.mha.gov.in/",
            "https://www.mod.gov.in/",
            "https://www.mohfw.gov.in/",
            "https://www.mea.gov.in/",
            "https://www.neda.gov.ph/",
            "https://www.gov.ph/",
            "https://www.thaigov.go.th/",
            "https://www.mfa.go.th/",
            "https://www.mfa.gov.vn/",
            "https://www.chinhphu.vn/",
            "https://www.indonesia.go.id/",
            "https://www.kemendagri.go.id/",
            "https://www.malaysia.gov.my/",
            "https://www.jpm.gov.my/",
            "https://www.pmo.gov.sg/",
            "https://www.mfa.gov.sg/",
            "https://www.mfa.gov.bn/",
            "https://www.gov.bn/",
            "https://www.mfa.gov.np/",
            "https://www.nepal.gov.np/",
            "https://www.mfa.gov.bd/",
            "https://www.bangladesh.gov.bd/",
            "https://www.mfa.gov.lk/",
            "https://www.gov.lk/",
            "https://www.mfa.gov.mm/",
            "https://www.mfa.gov.kh/",
            "https://www.mfaic.gov.kh/",
            "https://www.mfa.gov.la/",
            "https://www.gov.la/",
            "https://www.mfa.gov.mn/",
            "https://www.gov.mn/",
            "https://www.mfa.gov.kz/",
            "https://www.gov.kz/",
            "https://www.mfa.gov.uz/",
            "https://www.gov.uz/",
            "https://www.mfa.gov.az/",
            "https://www.gov.az/",
            "https://www.mfa.gov.ge/",
            "https://www.gov.ge/",
            "https://www.mfa.am/",
            "https://www.gov.am/",
        ],
        "asia_gov",
    )

    # --- Open-source & foundations ---
    add(
        [
            "https://www.linuxfoundation.org/",
            "https://www.apache.org/",
            "https://www.eclipse.org/",
            "https://www.qt.io/",
            "https://www.kde.org/",
            "https://www.gnome.org/",
            "https://www.blender.org/",
            "https://www.videolan.org/",
            "https://www.libreoffice.org/",
            "https://www.openstreetmap.org/",
            "https://www.osmfoundation.org/",
            "https://www.apache.org/foundation/",
            "https://www.cncf.io/",
            "https://www.openstack.org/",
            "https://www.jenkins.io/",
            "https://www.ansible.com/",
            "https://www.hashicorp.com/",
            "https://www.puppet.com/",
            "https://www.chef.io/",
            "https://www.saltproject.io/",
            "https://www.vagrantup.com/",
            "https://www.virtualbox.org/",
            "https://www.qemu.org/",
            "https://www.wireshark.org/",
            "https://www.nmap.org/",
            "https://www.metasploit.com/",
            "https://www.snort.org/",
            "https://www.suricata.io/",
            "https://www.zaproxy.org/",
            "https://www.curl.se/",
            "https://www.openssl.org/",
            "https://www.letsencrypt.org/",
            "https://www.certbot.eff.org/",
        ],
        "opensource_foundation",
    )

    # --- Healthcare / research (official) ---
    add(
        [
            "https://www.mayoclinic.org/",
            "https://www.clevelandclinic.org/",
            "https://www.johnshopkins.edu/",
            "https://www.massgeneral.org/",
            "https://www.nhs.uk/",
            "https://www.who.int/",
            "https://www.unaids.org/",
            "https://www.gavi.org/",
            "https://www.coalitionforinnovation.org/",
            "https://www.cancer.gov/",
            "https://www.nhlbi.nih.gov/",
            "https://www.niddk.nih.gov/",
            "https://www.nei.nih.gov/",
            "https://www.ninds.nih.gov/",
            "https://www.nimh.nih.gov/",
            "https://www.ncbi.nlm.nih.gov/",
            "https://pubmed.ncbi.nlm.nih.gov/",
            "https://www.ema.europa.eu/",
            "https://www.tga.gov.au/",
            "https://www.health.gov.au/",
        ],
        "health_research",
    )

    # --- Consulting / audit / professional services ---
    add(
        [
            "https://www.mckinsey.com/",
            "https://www.bcg.com/",
            "https://www.bain.com/",
            "https://www2.deloitte.com/",
            "https://www.pwc.com/",
            "https://www.ey.com/",
            "https://www.kpmg.com/",
            "https://www.grantthornton.com/",
            "https://www.bdo.com/",
            "https://www.rsm.global/",
            "https://www.accenture.com/",
            "https://www.capgemini.com/",
            "https://www.cognizant.com/",
            "https://www.infosys.com/",
            "https://www.wipro.com/",
            "https://www.techmahindra.com/",
            "https://www.hcltech.com/",
            "https://www.nttdata.com/",
            "https://www.fujitsu.com/",
            "https://www.hitachi.com/",
            "https://www.ricoh.com/",
            "https://www.kyocera.com/",
            "https://www.canon.com/",
            "https://www.epson.com/",
            "https://www.brother.com/",
            "https://www.xerox.com/",
        ],
        "consulting_it_services",
    )

    return p


def main() -> None:
    out_path = _REPO / "data" / "evaluation" / "simple_legit_urls.jsonl"
    pairs = _all_pairs()
    rows = _dedupe_rows(pairs)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    cats: Dict[str, int] = {}
    for r in rows:
        c = r.get("category", "")
        cats[c] = cats.get(c, 0) + 1
    print(f"Wrote {len(rows)} unique canonical URLs -> {out_path}")
    print("Top categories:", dict(sorted(cats.items(), key=lambda x: -x[1])[:15]))
    if len(rows) < 500:
        sys.exit(f"ERROR: only {len(rows)} rows; need >= 500")
    if len(rows) < 800:
        print(f"WARNING: only {len(rows)} rows; target band is 800–1000 for stronger influence.", file=sys.stderr)


if __name__ == "__main__":
    main()
