"""Copy the demo into the portfolio repo and wire it into the two pages (rebuild Phase 6).

  python demo/install_portfolio.py <path to bharathnaveen-portfolio>

Idempotent: re-running replaces the demo section between its markers and leaves everything else alone.
  * assets/phishing-demo/   model-core.json, model-rf.bin.gz, phishguard-engine.js, demo.js, demo.css
  * projects/phishing-detection-system.html
        demo section (demo/build/demo-section.html) as the first section of <main>, its stylesheet and
        scripts, and a "Try it" button in the hero
  * index.html   a "Try it" link on the phishing project card
"""

from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "demo" / "build"
START, END = "<!-- phishing-demo:start (generated by demo/install_portfolio.py in the phishing repo) -->", "<!-- phishing-demo:end -->"


def sub_once(pattern: str, repl: str, text: str, what: str) -> str:
    new, n = re.subn(pattern, repl, text, count=1, flags=re.S)
    if n != 1:
        raise SystemExit(f"could not place {what}")
    return new


def main() -> None:
    site = Path(sys.argv[1]).resolve()
    page = site / "projects" / "phishing-detection-system.html"
    home = site / "index.html"
    assets = site / "assets" / "phishing-demo"
    assets.mkdir(parents=True, exist_ok=True)
    for src in (BUILD / "model-core.json", BUILD / "model-rf.bin.gz", ROOT / "demo" / "js" / "phishguard-engine.js",
                ROOT / "demo" / "web" / "demo.js", ROOT / "demo" / "web" / "demo.css"):
        shutil.copyfile(src, assets / src.name)

    html = page.read_text(encoding="utf-8")
    section = (BUILD / "demo-section.html").read_text(encoding="utf-8")
    block = f"{START}\n{section}{END}"
    if START in html:
        html = re.sub(re.escape(START) + ".*?" + re.escape(END), lambda m: block, html, count=1, flags=re.S)
    else:
        html = sub_once(r'(<main class="pwrap">)', lambda m: m.group(1) + "\n" + block + "\n", html, "demo section")
    css = '<link rel="stylesheet" href="../assets/phishing-demo/demo.css">'
    if css not in html:
        html = sub_once(r'(<link rel="stylesheet" href="\.\./assets/project\.css">)', lambda m: m.group(1) + "\n" + css, html, "demo stylesheet")
    js = '<script src="../assets/phishing-demo/phishguard-engine.js" defer></script>\n<script src="../assets/phishing-demo/demo.js" defer></script>'
    if "phishing-demo/demo.js" not in html:
        html = sub_once(r"(</body>)", lambda m: js + "\n" + m.group(1), html, "demo scripts")
    hero_btn = '<a class="btn btn-ghost" href="#demo">Try it</a>'
    if hero_btn not in html:
        html = sub_once(r'(<a class="btn btn-ghost" href="\.\./index\.html#work">All projects</a>)', lambda m: hero_btn + m.group(1), html, "hero button")
    page.write_text(html, encoding="utf-8", newline="")

    h = home.read_text(encoding="utf-8")
    card_link = '<a class="trylink" href="projects/phishing-detection-system.html#demo">Try it</a>'
    if card_link not in h:
        h = sub_once(r'(<a class="link" href="projects/phishing-detection-system\.html">View project <svg.*?</svg></a>)',
                     lambda m: m.group(1) + card_link, h, "homepage Try it link")
    style = ".pcard .pfoot .trylink{position:relative; z-index:2; font-weight:600; font-size:13.5px; padding:6px 12px; border-radius:9px; border:1px solid var(--accent); color:var(--accent-strong); margin-left:auto}\n.pcard .pfoot .trylink:hover{background:var(--accent-wash)}\n"
    if ".pcard .pfoot .trylink" not in h:
        h = sub_once(r"(\.pcard:hover \.pfoot \.link\{text-decoration:underline\}\n)", lambda m: m.group(1) + style, h, "homepage Try it style")
    home.write_text(h, encoding="utf-8", newline="")
    print("installed into", site)


if __name__ == "__main__":
    main()
